import React from 'react'
import './globals.css'
import Header from "./components/Header"
import Footer from "./components/Footer"


export const metadata = {
  title: 'Distance to Heathrow',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <Header/>
        <div className="flex-grow">
            {children}
        </div>
         <Footer/>
      </body>
    </html>
  )
}
